feat: add chart widget
Eeap/Mobile-Billing-Dashboard pull request #8
Opened 2023-10-30 14:49 UTC by Eeap

## Description
https://app.flchart.dev/#/line을 참고해서 chart를 사용했는데 아래 사진처럼 밋밋한기도 하고 데이터가 소수점 단위로 왔을 경우 저렇게 거의 바닥을 기는데 이럴 경우 maxY를 주석처리하게 된다면 표를 벗어나게 되는 경우가 존재합니다..
차트를 긴 컨테이너로 묶고 그 안에 차트를 나열하는게 깔끔할지.. 또 차트의 크기를 작게 하는게 나을지?? 피드백 주시면 감사하겠습니다 ㅎ^^
<img width="362" alt="image" src="https://github.com/Eeap/Mobile-Billing-Dashboard/assets/42088290/53931024-186e-49f2-aedb-8de08aedf565">

## Related Issue

Closes #7

2023-10-31 05:41 UTC, bluejoyq requested changes
열심히 노력한 흔적이 보이네요 ^^

2023-10-31 05:41 UTC, bluejoyq commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
nullable인 이유가 궁금해요

2023-10-31 05:41 UTC, bluejoyq commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    Map<String?, List<Resource>> _mapData = {};
지금 PR이랑 별개긴한데, `json_serializable` 패키지를 사용해서 파싱 과정을 자동화하면 어떨까요?

2023-10-31 05:41 UTC, bluejoyq commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
데이터에 null이 들어갈 일이 있나요?

2023-10-31 05:41 UTC, bluejoyq commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +  List<String> makeDayData(List<Resource>? mapResources) {
이렇게 쓸거면 위에서 null 가능성을 체크하고 이 함수를 호출하는게 어떨까요?!

2023-10-31 05:41 UTC, bluejoyq commented on front_end/lib/src/presentation/widgets/resource_chart_widget.dart
> +          double.parse(mapResources![i.toInt()].amount!).toStringAsFixed(10));
amount가 null일 가능성이 없다면 Resource 모델에서 nullable을 제거하는게 어떤가요?

2023-10-31 05:41 UTC, bluejoyq commented on front_end/lib/src/presentation/widgets/resource_chart_widget.dart
> +          double.parse(mapResources![i.toInt()].amount!).toStringAsFixed(10));
소수점은 반올림으로 어느정도 걸러주면 차트가 이쁘게 나올 것 같아요.

2023-11-01 01:52 UTC, Eeap commented on front_end/lib/src/presentation/widgets/resource_chart_widget.dart
> +          double.parse(mapResources![i.toInt()].amount!).toStringAsFixed(10));
그렇게 했더니 거의 다 0처리 되어버려요

2023-11-01 01:52 UTC, Eeap commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
사용자가 리소스를 하나도 안사용했을 경우 null이 될 수도 있어요

2023-11-01 01:53 UTC, Eeap commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    Map<String?, List<Resource>> _mapData = {};
흠 .. 어떤 식으로 자동화 한다는 건지 이해를 못했어요.. response을 받을때마다 자동으로 저렇게 만들어주는 toJson을 말하는건가요?

2023-11-01 06:00 UTC, bluejoyq commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
그러면 `List<Resource>`가 nullable인게 아니라 `List<Resource?>`가 되야하는거 아닌가요?

2023-11-01 06:01 UTC, bluejoyq commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    Map<String?, List<Resource>> _mapData = {};
네 정의한 클래스 형태에 따라 파싱 과정을 해주는 파일을 자동으로 생성해주는 패키지입니다.

2023-11-01 06:02 UTC, bluejoyq commented on front_end/lib/src/presentation/widgets/resource_chart_widget.dart
> +          double.parse(mapResources![i.toInt()].amount!).toStringAsFixed(10));
근데 이건 어쩔수 없는듯. 요금이 거의 안나오는 계정을 상대로 테스트해서 그럭너 아닐까요.
0.1 미만은 0.1로 고정하고 y 라벨을 `0.1<` 이런 느낌은 어때요

2023-11-04 13:21 UTC, Eeap commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
음 `List<Resource>` 이 부분은 리소스의 날짜별 데이터 리스트라서 안오려면 List 전체가 안오는게 맞아요 ㅎㅎ..

2023-11-04 13:31 UTC, bluejoyq commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
@Eeap 데이터 형태를 map으로 가지고 있는건 어떤가요 Map<string(date), List<Resource>> 일케?

2023-11-05 02:22 UTC, Eeap commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
이렇게 한 이유가 리소스 별로 날짜 순으로 데이터를 갖고 있게 하려고 한거여서.. 너무 지저분해보이나 타입이?

2023-11-05 03:13 UTC, bluejoyq commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
아 나 이해완료. 리소스 이름을 이넘으로 가지는 Map<string(리소스 이름 이넘),List>이면 더 좋을 것 같아요

2023-11-05 04:14 UTC, Eeap commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
근데 이넘 타입 같은 경우 미리 정의를 해야하지 않아? AWS resource 종류도 많고 어떤 리소스가 올지 몰라서 string으로 쓰긴 했어..
그리고 궁금한거는 flutter에선 nullable을 낭비하면 안되ㅡㄴㄴ건가? 초기 선언을 안하고 하다보니 어쩔 수 없이 ? 를 다 넣어주긴 했는데

2023-11-05 04:15 UTC, bluejoyq commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
노노 리모트 소스에서 데이터 가져오는거니까 null은 어쩔수 없다고 생각하는데, list list가 좀 그래요

2023-11-05 04:31 UTC, Eeap commented on front_end/lib/src/presentation/views/aws_billing_dashboard_view.dart
> +    List<List<Resource>?> result = [];
그건 저도 공감합니다.. 하지만 스크롤 뷰에서 인덱스로 접근해가지고 어쩔 수 없이ㅠ.. 안에 리스트를 하나 더 넣어놓은거 리소스 별로 데이터를 list화하기 위해서였습니다 선생님..

2023-11-05 04:32 UTC, Eeap commented on front_end/lib/src/presentation/widgets/resource_chart_widget.dart
> +          double.parse(mapResources![i.toInt()].amount!).toStringAsFixed(10));
흠.. 이것좀 고민해봐야겠어요 지금 - 데이터는 왜있는지 몰겠지만 있어서

2023-11-06 03:42 UTC, merged